apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart.releaseName }}
  labels:
{{ include "sampleapp.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.chart.releaseName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
